### ISSUE TITLE
This is a test issue

### ISSUE THREAD

**Issue by lukebaker** [lukebaker/protected-branch-testing#16]
Test issue for testing notifications

**Comment by lukebaker-travis** [comment]
Test comment.

**Comment by lukebaker-travis** [comment]
@lukebaker are you getting this?

**Comment by lukebaker-travis** [comment]
:shipit:

**Comment by lukebaker-travis** [comment]
Commenting on a closed issue

**Comment by lukebaker-travis** [comment]
Another comment on the closed issue.

**Comment by lukebaker-travis** [comment]
Mentioning you appears to subscribe you, @lukebaker
